version: 2
jobs:
  build:
    docker:
      - image: circleci/android:api-25-alpha
    working_directory: ~/repo
    steps:
      - checkout:
          path: ~/repo
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - run:
          name: Run Detekt
          command: ./gradlew detekt
      - run:
          name: Run Unit tests
          command: ./gradlew test